CREATE TABLE `spare_parts` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`name` text NOT NULL,
	`brand` text NOT NULL,
	`model` text NOT NULL,
	`catalog_number` text NOT NULL,
	`application` text NOT NULL,
	`delivery` text NOT NULL,
	`price_without_vat` real NOT NULL,
	`price_with_vat` real NOT NULL,
	`discount` real DEFAULT 0 NOT NULL,
	`image_url` text NOT NULL,
	`spec1` text NOT NULL,
	`spec2` text NOT NULL,
	`spec3` text NOT NULL,
	`spec4` text NOT NULL,
	`spec5` text NOT NULL,
	`spec6` text NOT NULL,
	`spec7` text NOT NULL
);
